contractor_rate: 0.5
default_num_contractors: 2
default_num_customers: 10
delivery_additional_time: 10
errand_rates:
  Cut Grass: 2
  Delivery: 2
  Detail Car: 2.5
  Dog Walk: 1.5
  Grocery Shopping: 1.5
  Moving: 3.5
  Outing: 3
errand_types:
- base_time: 15
  disincentive:
    days: 14
    type: percentage
    value: 25.0
  incentive: 1.2
  name: DELIVERY
- base_time: 20
  disincentive:
    days: 14
    type: percentage
    value: 0.0
  incentive: 1.1
  name: DOG_WALK
- base_time: 60
  disincentive:
    days: 14
    type: percentage
    value: 0.0
  incentive: 1.3
  name: CUT_GRASS
- base_time: 180
  disincentive:
    days: 14
    type: percentage
    value: 10.0
  incentive: 1.2
  name: DETAIL_CAR
- base_time: 240
  disincentive:
    days: 14
    type: percentage
    value: 10.0
  incentive: 1.05
  name: OUTING
- base_time: 420
  disincentive:
    days: 14
    type: percentage
    value: 100.0
  incentive: 1.5
  name: MOVING
max_incentive_multiplier: 1.5
num_contractors: 2
num_customers: 10
optimization:
  log_search_progress: true
  max_time_in_seconds: 60
scheduling_days: 14
work_end_time: 1020
work_start_time: 480
