# Configuration file for the Synthetic Errands Scheduler

# Errand Types
# This section defines the different types of errands available in the system.
# Each errand type has the following properties:
#   - name: The name of the errand type
#   - base_time: The basic time (in minutes) it takes to complete this errand
#   - incentive: The multiplier applied to the base rate for same-day service
#   - disincentive: The penalty applied for late completion (can be null if no penalty)
#     - type: Can be 'percentage' or 'fixed'
#     - value: The amount of the penalty (percentage or fixed amount)
#     - days: The number of days after which the penalty applies
errand_types:
  - name: Delivery
    base_time: 10
    incentive: 1.2
    disincentive:
      type: percentage
      value: 25
      days: 14
  - name: Dog Walk
    base_time: 20
    incentive: 1.1
    disincentive: null
  - name: Cut Grass
    base_time: 10
    incentive: 1.3
    disincentive: null
  - name: Detail Car
    base_time: 15
    incentive: 1.2
    disincentive:
      type: percentage
      value: 10
      days: 14
  - name: Outing
    base_time: 15
    incentive: 1.05
    disincentive:
      type: percentage
      value: 10
      days: 14
  - name: Moving
    base_time: 120
    incentive: 1.5
    disincentive:
      type: fixed
      value: 300
      days: 14

# Errand Rates ($ per minute)
# This section defines the base rate charged for each type of errand.
errand_rates:
  Delivery: 2
  Dog Walk: 1.5
  Cut Grass: 2
  Detail Car: 2.5
  Outing: 3
  Moving: 3.5
  Grocery Shopping: 1.5

# Additional time for specific errand types (in minutes)
# Some errands may require extra time beyond their base time.
# Currently, only Delivery has an additional time requirement.
delivery_additional_time: 10

# Working hours
# These values define the start and end of the working day in minutes from midnight.
# 480 minutes = 8:00 AM, 1020 minutes = 5:00 PM
work_start_time: 480
work_end_time: 1020

# Default problem generation parameters
# These values are used when generating random problem instances.
default_num_customers: 10
default_num_contractors: 2

# Scheduling period
# The number of days to schedule errands for.
scheduling_days: 14

# Maximum incentive multiplier
# This caps the maximum incentive that can be applied for same-day service.
max_incentive_multiplier: 1.5

# Optimization parameters
# These parameters are used by the optimization algorithm.
optimization:
  # Maximum time (in seconds) the optimizer will run before stopping.
  max_time_in_seconds: 60
  # Whether to log the progress of the optimization search.
  log_search_progress: true